/*
 * ID4i API
 * HTTP API Documentation for ID4i
 *
 * OpenAPI spec version: 0.2.0
 * Contact: info@bluerain.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.id4i.api;

import de.id4i.ApiCallback;
import de.id4i.ApiClient;
import de.id4i.ApiException;
import de.id4i.ApiResponse;
import de.id4i.Configuration;
import de.id4i.Pair;
import de.id4i.ProgressRequestBody;
import de.id4i.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import de.id4i.api.model.AddApiKeyPrivilegeRequest;
import de.id4i.api.model.ApiError;
import de.id4i.api.model.ApiKeyChangeRequest;
import de.id4i.api.model.ApiKeyCreationRequest;
import de.id4i.api.model.ApiKeyPresentation;
import de.id4i.api.model.ApiKeyPrivilegeInfoResponse;
import de.id4i.api.model.ApiKeyPrivilegePaginatedResponse;
import de.id4i.api.model.Id4nPresentationPaginatedResponse;
import de.id4i.api.model.ListOfId4ns;
import de.id4i.api.model.PaginatedApiKeyResponse;
import de.id4i.api.model.RemoveApiKeyPrivilegeRequest;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ApiKeysApi {
    private ApiClient apiClient;

    public ApiKeysApi() {
        this(Configuration.getDefaultApiClient());
    }

    public ApiKeysApi(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return apiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    /**
     * Build call for addApiKeyPrivilege
     * @param key key (required)
     * @param addApiKeyPrivilegeRequest addApiKeyPrivilegeRequest (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call addApiKeyPrivilegeCall(String key, AddApiKeyPrivilegeRequest addApiKeyPrivilegeRequest, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = addApiKeyPrivilegeRequest;
        
        // create path and map variables
        String localVarPath = "/api/v1/apikeys/{key}/privileges"
            .replaceAll("\\{" + "key" + "\\}", apiClient.escapeString(key.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/xml", "application/json;charset=UTF-8"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/xml", "application/json;charset=UTF-8"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "Authorization" };
        return apiClient.buildCall(localVarPath, "POST", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call addApiKeyPrivilegeValidateBeforeCall(String key, AddApiKeyPrivilegeRequest addApiKeyPrivilegeRequest, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'key' is set
        if (key == null) {
            throw new ApiException("Missing the required parameter 'key' when calling addApiKeyPrivilege(Async)");
        }
        
        // verify the required parameter 'addApiKeyPrivilegeRequest' is set
        if (addApiKeyPrivilegeRequest == null) {
            throw new ApiException("Missing the required parameter 'addApiKeyPrivilegeRequest' when calling addApiKeyPrivilege(Async)");
        }
        
        
        com.squareup.okhttp.Call call = addApiKeyPrivilegeCall(key, addApiKeyPrivilegeRequest, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * Add privilege
     * 
     * @param key key (required)
     * @param addApiKeyPrivilegeRequest addApiKeyPrivilegeRequest (required)
     * @return ApiError
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiError addApiKeyPrivilege(String key, AddApiKeyPrivilegeRequest addApiKeyPrivilegeRequest) throws ApiException {
        ApiResponse<ApiError> resp = addApiKeyPrivilegeWithHttpInfo(key, addApiKeyPrivilegeRequest);
        return resp.getData();
    }

    /**
     * Add privilege
     * 
     * @param key key (required)
     * @param addApiKeyPrivilegeRequest addApiKeyPrivilegeRequest (required)
     * @return ApiResponse&lt;ApiError&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<ApiError> addApiKeyPrivilegeWithHttpInfo(String key, AddApiKeyPrivilegeRequest addApiKeyPrivilegeRequest) throws ApiException {
        com.squareup.okhttp.Call call = addApiKeyPrivilegeValidateBeforeCall(key, addApiKeyPrivilegeRequest, null, null);
        Type localVarReturnType = new TypeToken<ApiError>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Add privilege (asynchronously)
     * 
     * @param key key (required)
     * @param addApiKeyPrivilegeRequest addApiKeyPrivilegeRequest (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call addApiKeyPrivilegeAsync(String key, AddApiKeyPrivilegeRequest addApiKeyPrivilegeRequest, final ApiCallback<ApiError> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = addApiKeyPrivilegeValidateBeforeCall(key, addApiKeyPrivilegeRequest, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<ApiError>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for addApiKeyPrivilegeForId4ns
     * @param key key (required)
     * @param privilege privilege (required)
     * @param id4ns id4ns (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call addApiKeyPrivilegeForId4nsCall(String key, String privilege, ListOfId4ns id4ns, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = id4ns;
        
        // create path and map variables
        String localVarPath = "/api/v1/apikeys/{key}/privileges/{privilege}/id4ns"
            .replaceAll("\\{" + "key" + "\\}", apiClient.escapeString(key.toString()))
            .replaceAll("\\{" + "privilege" + "\\}", apiClient.escapeString(privilege.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/xml", "application/json;charset=UTF-8"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/xml", "application/json;charset=UTF-8"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "Authorization" };
        return apiClient.buildCall(localVarPath, "POST", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call addApiKeyPrivilegeForId4nsValidateBeforeCall(String key, String privilege, ListOfId4ns id4ns, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'key' is set
        if (key == null) {
            throw new ApiException("Missing the required parameter 'key' when calling addApiKeyPrivilegeForId4ns(Async)");
        }
        
        // verify the required parameter 'privilege' is set
        if (privilege == null) {
            throw new ApiException("Missing the required parameter 'privilege' when calling addApiKeyPrivilegeForId4ns(Async)");
        }
        
        // verify the required parameter 'id4ns' is set
        if (id4ns == null) {
            throw new ApiException("Missing the required parameter 'id4ns' when calling addApiKeyPrivilegeForId4ns(Async)");
        }
        
        
        com.squareup.okhttp.Call call = addApiKeyPrivilegeForId4nsCall(key, privilege, id4ns, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * Add ID4ns of a privilege
     * 
     * @param key key (required)
     * @param privilege privilege (required)
     * @param id4ns id4ns (required)
     * @return ApiError
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiError addApiKeyPrivilegeForId4ns(String key, String privilege, ListOfId4ns id4ns) throws ApiException {
        ApiResponse<ApiError> resp = addApiKeyPrivilegeForId4nsWithHttpInfo(key, privilege, id4ns);
        return resp.getData();
    }

    /**
     * Add ID4ns of a privilege
     * 
     * @param key key (required)
     * @param privilege privilege (required)
     * @param id4ns id4ns (required)
     * @return ApiResponse&lt;ApiError&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<ApiError> addApiKeyPrivilegeForId4nsWithHttpInfo(String key, String privilege, ListOfId4ns id4ns) throws ApiException {
        com.squareup.okhttp.Call call = addApiKeyPrivilegeForId4nsValidateBeforeCall(key, privilege, id4ns, null, null);
        Type localVarReturnType = new TypeToken<ApiError>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Add ID4ns of a privilege (asynchronously)
     * 
     * @param key key (required)
     * @param privilege privilege (required)
     * @param id4ns id4ns (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call addApiKeyPrivilegeForId4nsAsync(String key, String privilege, ListOfId4ns id4ns, final ApiCallback<ApiError> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = addApiKeyPrivilegeForId4nsValidateBeforeCall(key, privilege, id4ns, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<ApiError>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for createNewApiKey
     * @param creationRequest API key to be created. (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call createNewApiKeyCall(ApiKeyCreationRequest creationRequest, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = creationRequest;
        
        // create path and map variables
        String localVarPath = "/api/v1/apikeys";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/xml", "application/json;charset=UTF-8"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/xml", "application/json;charset=UTF-8"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "Authorization" };
        return apiClient.buildCall(localVarPath, "POST", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call createNewApiKeyValidateBeforeCall(ApiKeyCreationRequest creationRequest, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'creationRequest' is set
        if (creationRequest == null) {
            throw new ApiException("Missing the required parameter 'creationRequest' when calling createNewApiKey(Async)");
        }
        
        
        com.squareup.okhttp.Call call = createNewApiKeyCall(creationRequest, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * Create API key
     * Creation of a new API key.
     * @param creationRequest API key to be created. (required)
     * @return ApiKeyPresentation
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiKeyPresentation createNewApiKey(ApiKeyCreationRequest creationRequest) throws ApiException {
        ApiResponse<ApiKeyPresentation> resp = createNewApiKeyWithHttpInfo(creationRequest);
        return resp.getData();
    }

    /**
     * Create API key
     * Creation of a new API key.
     * @param creationRequest API key to be created. (required)
     * @return ApiResponse&lt;ApiKeyPresentation&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<ApiKeyPresentation> createNewApiKeyWithHttpInfo(ApiKeyCreationRequest creationRequest) throws ApiException {
        com.squareup.okhttp.Call call = createNewApiKeyValidateBeforeCall(creationRequest, null, null);
        Type localVarReturnType = new TypeToken<ApiKeyPresentation>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Create API key (asynchronously)
     * Creation of a new API key.
     * @param creationRequest API key to be created. (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call createNewApiKeyAsync(ApiKeyCreationRequest creationRequest, final ApiCallback<ApiKeyPresentation> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = createNewApiKeyValidateBeforeCall(creationRequest, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<ApiKeyPresentation>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for deleteApiKey
     * @param key The API key to delete. (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call deleteApiKeyCall(String key, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/api/v1/apikeys/{key}"
            .replaceAll("\\{" + "key" + "\\}", apiClient.escapeString(key.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/xml", "application/json;charset=UTF-8"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/xml", "application/json;charset=UTF-8"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "Authorization" };
        return apiClient.buildCall(localVarPath, "DELETE", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call deleteApiKeyValidateBeforeCall(String key, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'key' is set
        if (key == null) {
            throw new ApiException("Missing the required parameter 'key' when calling deleteApiKey(Async)");
        }
        
        
        com.squareup.okhttp.Call call = deleteApiKeyCall(key, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * Delete API key
     * Deletion of an API key.
     * @param key The API key to delete. (required)
     * @return ApiError
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiError deleteApiKey(String key) throws ApiException {
        ApiResponse<ApiError> resp = deleteApiKeyWithHttpInfo(key);
        return resp.getData();
    }

    /**
     * Delete API key
     * Deletion of an API key.
     * @param key The API key to delete. (required)
     * @return ApiResponse&lt;ApiError&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<ApiError> deleteApiKeyWithHttpInfo(String key) throws ApiException {
        com.squareup.okhttp.Call call = deleteApiKeyValidateBeforeCall(key, null, null);
        Type localVarReturnType = new TypeToken<ApiError>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Delete API key (asynchronously)
     * Deletion of an API key.
     * @param key The API key to delete. (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call deleteApiKeyAsync(String key, final ApiCallback<ApiError> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = deleteApiKeyValidateBeforeCall(key, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<ApiError>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for getApiKey
     * @param key The API key to show. (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call getApiKeyCall(String key, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/api/v1/apikeys/{key}"
            .replaceAll("\\{" + "key" + "\\}", apiClient.escapeString(key.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/xml", "application/json;charset=UTF-8"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/xml", "application/json;charset=UTF-8"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "Authorization" };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call getApiKeyValidateBeforeCall(String key, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'key' is set
        if (key == null) {
            throw new ApiException("Missing the required parameter 'key' when calling getApiKey(Async)");
        }
        
        
        com.squareup.okhttp.Call call = getApiKeyCall(key, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * Show API key
     * Showing the details of an API key.
     * @param key The API key to show. (required)
     * @return ApiKeyPresentation
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiKeyPresentation getApiKey(String key) throws ApiException {
        ApiResponse<ApiKeyPresentation> resp = getApiKeyWithHttpInfo(key);
        return resp.getData();
    }

    /**
     * Show API key
     * Showing the details of an API key.
     * @param key The API key to show. (required)
     * @return ApiResponse&lt;ApiKeyPresentation&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<ApiKeyPresentation> getApiKeyWithHttpInfo(String key) throws ApiException {
        com.squareup.okhttp.Call call = getApiKeyValidateBeforeCall(key, null, null);
        Type localVarReturnType = new TypeToken<ApiKeyPresentation>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Show API key (asynchronously)
     * Showing the details of an API key.
     * @param key The API key to show. (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call getApiKeyAsync(String key, final ApiCallback<ApiKeyPresentation> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = getApiKeyValidateBeforeCall(key, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<ApiKeyPresentation>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for listAllApiKeyPrivileges
     * @param id4nConcerning id4nConcerning (optional)
     * @param offset Start with the n-th element (optional)
     * @param limit The maximum count of returned elements (optional)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call listAllApiKeyPrivilegesCall(Boolean id4nConcerning, Integer offset, Integer limit, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/api/v1/apikeys/privileges";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        if (id4nConcerning != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("", "id4nConcerning", id4nConcerning));
        if (offset != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("", "offset", offset));
        if (limit != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("", "limit", limit));

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/xml", "application/json;charset=UTF-8"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/xml", "application/json;charset=UTF-8"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "Authorization" };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call listAllApiKeyPrivilegesValidateBeforeCall(Boolean id4nConcerning, Integer offset, Integer limit, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        
        com.squareup.okhttp.Call call = listAllApiKeyPrivilegesCall(id4nConcerning, offset, limit, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * List all privileges
     * Listing all possible API key privileges.
     * @param id4nConcerning id4nConcerning (optional)
     * @param offset Start with the n-th element (optional)
     * @param limit The maximum count of returned elements (optional)
     * @return ApiKeyPrivilegeInfoResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiKeyPrivilegeInfoResponse listAllApiKeyPrivileges(Boolean id4nConcerning, Integer offset, Integer limit) throws ApiException {
        ApiResponse<ApiKeyPrivilegeInfoResponse> resp = listAllApiKeyPrivilegesWithHttpInfo(id4nConcerning, offset, limit);
        return resp.getData();
    }

    /**
     * List all privileges
     * Listing all possible API key privileges.
     * @param id4nConcerning id4nConcerning (optional)
     * @param offset Start with the n-th element (optional)
     * @param limit The maximum count of returned elements (optional)
     * @return ApiResponse&lt;ApiKeyPrivilegeInfoResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<ApiKeyPrivilegeInfoResponse> listAllApiKeyPrivilegesWithHttpInfo(Boolean id4nConcerning, Integer offset, Integer limit) throws ApiException {
        com.squareup.okhttp.Call call = listAllApiKeyPrivilegesValidateBeforeCall(id4nConcerning, offset, limit, null, null);
        Type localVarReturnType = new TypeToken<ApiKeyPrivilegeInfoResponse>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * List all privileges (asynchronously)
     * Listing all possible API key privileges.
     * @param id4nConcerning id4nConcerning (optional)
     * @param offset Start with the n-th element (optional)
     * @param limit The maximum count of returned elements (optional)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call listAllApiKeyPrivilegesAsync(Boolean id4nConcerning, Integer offset, Integer limit, final ApiCallback<ApiKeyPrivilegeInfoResponse> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = listAllApiKeyPrivilegesValidateBeforeCall(id4nConcerning, offset, limit, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<ApiKeyPrivilegeInfoResponse>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for listAllApiKeysOfOrganization
     * @param organizationId The id of the organization to search in. (required)
     * @param offset Start with the n-th element (optional)
     * @param limit The maximum count of returned elements (optional)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call listAllApiKeysOfOrganizationCall(Long organizationId, Integer offset, Integer limit, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/api/v1/apikeys";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        if (organizationId != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("", "organizationId", organizationId));
        if (offset != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("", "offset", offset));
        if (limit != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("", "limit", limit));

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/xml", "application/json;charset=UTF-8"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/xml", "application/json;charset=UTF-8"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "Authorization" };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call listAllApiKeysOfOrganizationValidateBeforeCall(Long organizationId, Integer offset, Integer limit, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'organizationId' is set
        if (organizationId == null) {
            throw new ApiException("Missing the required parameter 'organizationId' when calling listAllApiKeysOfOrganization(Async)");
        }
        
        
        com.squareup.okhttp.Call call = listAllApiKeysOfOrganizationCall(organizationId, offset, limit, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * Find API key by organization
     * Finding all API key assigned to the specified organization in a paginated manner.
     * @param organizationId The id of the organization to search in. (required)
     * @param offset Start with the n-th element (optional)
     * @param limit The maximum count of returned elements (optional)
     * @return PaginatedApiKeyResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public PaginatedApiKeyResponse listAllApiKeysOfOrganization(Long organizationId, Integer offset, Integer limit) throws ApiException {
        ApiResponse<PaginatedApiKeyResponse> resp = listAllApiKeysOfOrganizationWithHttpInfo(organizationId, offset, limit);
        return resp.getData();
    }

    /**
     * Find API key by organization
     * Finding all API key assigned to the specified organization in a paginated manner.
     * @param organizationId The id of the organization to search in. (required)
     * @param offset Start with the n-th element (optional)
     * @param limit The maximum count of returned elements (optional)
     * @return ApiResponse&lt;PaginatedApiKeyResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<PaginatedApiKeyResponse> listAllApiKeysOfOrganizationWithHttpInfo(Long organizationId, Integer offset, Integer limit) throws ApiException {
        com.squareup.okhttp.Call call = listAllApiKeysOfOrganizationValidateBeforeCall(organizationId, offset, limit, null, null);
        Type localVarReturnType = new TypeToken<PaginatedApiKeyResponse>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Find API key by organization (asynchronously)
     * Finding all API key assigned to the specified organization in a paginated manner.
     * @param organizationId The id of the organization to search in. (required)
     * @param offset Start with the n-th element (optional)
     * @param limit The maximum count of returned elements (optional)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call listAllApiKeysOfOrganizationAsync(Long organizationId, Integer offset, Integer limit, final ApiCallback<PaginatedApiKeyResponse> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = listAllApiKeysOfOrganizationValidateBeforeCall(organizationId, offset, limit, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<PaginatedApiKeyResponse>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for listApiKeyPrivileges
     * @param key key (required)
     * @param offset Start with the n-th element (optional)
     * @param limit The maximum count of returned elements (optional)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call listApiKeyPrivilegesCall(String key, Integer offset, Integer limit, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/api/v1/apikeys/{key}/privileges"
            .replaceAll("\\{" + "key" + "\\}", apiClient.escapeString(key.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        if (offset != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("", "offset", offset));
        if (limit != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("", "limit", limit));

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/xml", "application/json;charset=UTF-8"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/xml", "application/json;charset=UTF-8"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "Authorization" };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call listApiKeyPrivilegesValidateBeforeCall(String key, Integer offset, Integer limit, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'key' is set
        if (key == null) {
            throw new ApiException("Missing the required parameter 'key' when calling listApiKeyPrivileges(Async)");
        }
        
        
        com.squareup.okhttp.Call call = listApiKeyPrivilegesCall(key, offset, limit, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * List privileges
     * 
     * @param key key (required)
     * @param offset Start with the n-th element (optional)
     * @param limit The maximum count of returned elements (optional)
     * @return ApiKeyPrivilegePaginatedResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiKeyPrivilegePaginatedResponse listApiKeyPrivileges(String key, Integer offset, Integer limit) throws ApiException {
        ApiResponse<ApiKeyPrivilegePaginatedResponse> resp = listApiKeyPrivilegesWithHttpInfo(key, offset, limit);
        return resp.getData();
    }

    /**
     * List privileges
     * 
     * @param key key (required)
     * @param offset Start with the n-th element (optional)
     * @param limit The maximum count of returned elements (optional)
     * @return ApiResponse&lt;ApiKeyPrivilegePaginatedResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<ApiKeyPrivilegePaginatedResponse> listApiKeyPrivilegesWithHttpInfo(String key, Integer offset, Integer limit) throws ApiException {
        com.squareup.okhttp.Call call = listApiKeyPrivilegesValidateBeforeCall(key, offset, limit, null, null);
        Type localVarReturnType = new TypeToken<ApiKeyPrivilegePaginatedResponse>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * List privileges (asynchronously)
     * 
     * @param key key (required)
     * @param offset Start with the n-th element (optional)
     * @param limit The maximum count of returned elements (optional)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call listApiKeyPrivilegesAsync(String key, Integer offset, Integer limit, final ApiCallback<ApiKeyPrivilegePaginatedResponse> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = listApiKeyPrivilegesValidateBeforeCall(key, offset, limit, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<ApiKeyPrivilegePaginatedResponse>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for listId4ns
     * @param key key (required)
     * @param privilege privilege (required)
     * @param offset Start with the n-th element (optional)
     * @param limit The maximum count of returned elements (optional)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call listId4nsCall(String key, String privilege, Integer offset, Integer limit, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/api/v1/apikeys/{key}/privileges/{privilege}/id4ns"
            .replaceAll("\\{" + "key" + "\\}", apiClient.escapeString(key.toString()))
            .replaceAll("\\{" + "privilege" + "\\}", apiClient.escapeString(privilege.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        if (offset != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("", "offset", offset));
        if (limit != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("", "limit", limit));

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/xml", "application/json;charset=UTF-8"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/xml", "application/json;charset=UTF-8"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "Authorization" };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call listId4nsValidateBeforeCall(String key, String privilege, Integer offset, Integer limit, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'key' is set
        if (key == null) {
            throw new ApiException("Missing the required parameter 'key' when calling listId4ns(Async)");
        }
        
        // verify the required parameter 'privilege' is set
        if (privilege == null) {
            throw new ApiException("Missing the required parameter 'privilege' when calling listId4ns(Async)");
        }
        
        
        com.squareup.okhttp.Call call = listId4nsCall(key, privilege, offset, limit, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * ID4ns of a privilege
     * Listing ID4ns of a id4n concerning privilege
     * @param key key (required)
     * @param privilege privilege (required)
     * @param offset Start with the n-th element (optional)
     * @param limit The maximum count of returned elements (optional)
     * @return Id4nPresentationPaginatedResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public Id4nPresentationPaginatedResponse listId4ns(String key, String privilege, Integer offset, Integer limit) throws ApiException {
        ApiResponse<Id4nPresentationPaginatedResponse> resp = listId4nsWithHttpInfo(key, privilege, offset, limit);
        return resp.getData();
    }

    /**
     * ID4ns of a privilege
     * Listing ID4ns of a id4n concerning privilege
     * @param key key (required)
     * @param privilege privilege (required)
     * @param offset Start with the n-th element (optional)
     * @param limit The maximum count of returned elements (optional)
     * @return ApiResponse&lt;Id4nPresentationPaginatedResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<Id4nPresentationPaginatedResponse> listId4nsWithHttpInfo(String key, String privilege, Integer offset, Integer limit) throws ApiException {
        com.squareup.okhttp.Call call = listId4nsValidateBeforeCall(key, privilege, offset, limit, null, null);
        Type localVarReturnType = new TypeToken<Id4nPresentationPaginatedResponse>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * ID4ns of a privilege (asynchronously)
     * Listing ID4ns of a id4n concerning privilege
     * @param key key (required)
     * @param privilege privilege (required)
     * @param offset Start with the n-th element (optional)
     * @param limit The maximum count of returned elements (optional)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call listId4nsAsync(String key, String privilege, Integer offset, Integer limit, final ApiCallback<Id4nPresentationPaginatedResponse> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = listId4nsValidateBeforeCall(key, privilege, offset, limit, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<Id4nPresentationPaginatedResponse>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for removeApiKeyPrivilege
     * @param key key (required)
     * @param removeApiKeyPrivilegeRequest removeApiKeyPrivilegeRequest (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call removeApiKeyPrivilegeCall(String key, RemoveApiKeyPrivilegeRequest removeApiKeyPrivilegeRequest, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = removeApiKeyPrivilegeRequest;
        
        // create path and map variables
        String localVarPath = "/api/v1/apikeys/{key}/privileges"
            .replaceAll("\\{" + "key" + "\\}", apiClient.escapeString(key.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/xml", "application/json;charset=UTF-8"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/xml", "application/json;charset=UTF-8"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "Authorization" };
        return apiClient.buildCall(localVarPath, "DELETE", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call removeApiKeyPrivilegeValidateBeforeCall(String key, RemoveApiKeyPrivilegeRequest removeApiKeyPrivilegeRequest, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'key' is set
        if (key == null) {
            throw new ApiException("Missing the required parameter 'key' when calling removeApiKeyPrivilege(Async)");
        }
        
        // verify the required parameter 'removeApiKeyPrivilegeRequest' is set
        if (removeApiKeyPrivilegeRequest == null) {
            throw new ApiException("Missing the required parameter 'removeApiKeyPrivilegeRequest' when calling removeApiKeyPrivilege(Async)");
        }
        
        
        com.squareup.okhttp.Call call = removeApiKeyPrivilegeCall(key, removeApiKeyPrivilegeRequest, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * Remove privilege
     * 
     * @param key key (required)
     * @param removeApiKeyPrivilegeRequest removeApiKeyPrivilegeRequest (required)
     * @return ApiError
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiError removeApiKeyPrivilege(String key, RemoveApiKeyPrivilegeRequest removeApiKeyPrivilegeRequest) throws ApiException {
        ApiResponse<ApiError> resp = removeApiKeyPrivilegeWithHttpInfo(key, removeApiKeyPrivilegeRequest);
        return resp.getData();
    }

    /**
     * Remove privilege
     * 
     * @param key key (required)
     * @param removeApiKeyPrivilegeRequest removeApiKeyPrivilegeRequest (required)
     * @return ApiResponse&lt;ApiError&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<ApiError> removeApiKeyPrivilegeWithHttpInfo(String key, RemoveApiKeyPrivilegeRequest removeApiKeyPrivilegeRequest) throws ApiException {
        com.squareup.okhttp.Call call = removeApiKeyPrivilegeValidateBeforeCall(key, removeApiKeyPrivilegeRequest, null, null);
        Type localVarReturnType = new TypeToken<ApiError>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Remove privilege (asynchronously)
     * 
     * @param key key (required)
     * @param removeApiKeyPrivilegeRequest removeApiKeyPrivilegeRequest (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call removeApiKeyPrivilegeAsync(String key, RemoveApiKeyPrivilegeRequest removeApiKeyPrivilegeRequest, final ApiCallback<ApiError> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = removeApiKeyPrivilegeValidateBeforeCall(key, removeApiKeyPrivilegeRequest, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<ApiError>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for removeApiKeyPrivilegeForId4ns
     * @param key key (required)
     * @param privilege privilege (required)
     * @param id4ns id4ns (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call removeApiKeyPrivilegeForId4nsCall(String key, String privilege, ListOfId4ns id4ns, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = id4ns;
        
        // create path and map variables
        String localVarPath = "/api/v1/apikeys/{key}/privileges/{privilege}/id4ns"
            .replaceAll("\\{" + "key" + "\\}", apiClient.escapeString(key.toString()))
            .replaceAll("\\{" + "privilege" + "\\}", apiClient.escapeString(privilege.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/xml", "application/json;charset=UTF-8"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/xml", "application/json;charset=UTF-8"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "Authorization" };
        return apiClient.buildCall(localVarPath, "DELETE", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call removeApiKeyPrivilegeForId4nsValidateBeforeCall(String key, String privilege, ListOfId4ns id4ns, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'key' is set
        if (key == null) {
            throw new ApiException("Missing the required parameter 'key' when calling removeApiKeyPrivilegeForId4ns(Async)");
        }
        
        // verify the required parameter 'privilege' is set
        if (privilege == null) {
            throw new ApiException("Missing the required parameter 'privilege' when calling removeApiKeyPrivilegeForId4ns(Async)");
        }
        
        // verify the required parameter 'id4ns' is set
        if (id4ns == null) {
            throw new ApiException("Missing the required parameter 'id4ns' when calling removeApiKeyPrivilegeForId4ns(Async)");
        }
        
        
        com.squareup.okhttp.Call call = removeApiKeyPrivilegeForId4nsCall(key, privilege, id4ns, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * Remove id4ns of a privilege
     * 
     * @param key key (required)
     * @param privilege privilege (required)
     * @param id4ns id4ns (required)
     * @return ApiError
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiError removeApiKeyPrivilegeForId4ns(String key, String privilege, ListOfId4ns id4ns) throws ApiException {
        ApiResponse<ApiError> resp = removeApiKeyPrivilegeForId4nsWithHttpInfo(key, privilege, id4ns);
        return resp.getData();
    }

    /**
     * Remove id4ns of a privilege
     * 
     * @param key key (required)
     * @param privilege privilege (required)
     * @param id4ns id4ns (required)
     * @return ApiResponse&lt;ApiError&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<ApiError> removeApiKeyPrivilegeForId4nsWithHttpInfo(String key, String privilege, ListOfId4ns id4ns) throws ApiException {
        com.squareup.okhttp.Call call = removeApiKeyPrivilegeForId4nsValidateBeforeCall(key, privilege, id4ns, null, null);
        Type localVarReturnType = new TypeToken<ApiError>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Remove id4ns of a privilege (asynchronously)
     * 
     * @param key key (required)
     * @param privilege privilege (required)
     * @param id4ns id4ns (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call removeApiKeyPrivilegeForId4nsAsync(String key, String privilege, ListOfId4ns id4ns, final ApiCallback<ApiError> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = removeApiKeyPrivilegeForId4nsValidateBeforeCall(key, privilege, id4ns, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<ApiError>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for updateApiKey
     * @param key The API key to be updated. (required)
     * @param apiKeyChange The new values to apply. (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call updateApiKeyCall(String key, ApiKeyChangeRequest apiKeyChange, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = apiKeyChange;
        
        // create path and map variables
        String localVarPath = "/api/v1/apikeys/{key}"
            .replaceAll("\\{" + "key" + "\\}", apiClient.escapeString(key.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/xml", "application/json;charset=UTF-8"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/xml", "application/json;charset=UTF-8"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "Authorization" };
        return apiClient.buildCall(localVarPath, "PUT", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call updateApiKeyValidateBeforeCall(String key, ApiKeyChangeRequest apiKeyChange, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'key' is set
        if (key == null) {
            throw new ApiException("Missing the required parameter 'key' when calling updateApiKey(Async)");
        }
        
        // verify the required parameter 'apiKeyChange' is set
        if (apiKeyChange == null) {
            throw new ApiException("Missing the required parameter 'apiKeyChange' when calling updateApiKey(Async)");
        }
        
        
        com.squareup.okhttp.Call call = updateApiKeyCall(key, apiKeyChange, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * Update API keys
     * API keys can be updated with new labels, and be activated and deactivated. The secret or UUID cannot be changed.
     * @param key The API key to be updated. (required)
     * @param apiKeyChange The new values to apply. (required)
     * @return ApiError
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiError updateApiKey(String key, ApiKeyChangeRequest apiKeyChange) throws ApiException {
        ApiResponse<ApiError> resp = updateApiKeyWithHttpInfo(key, apiKeyChange);
        return resp.getData();
    }

    /**
     * Update API keys
     * API keys can be updated with new labels, and be activated and deactivated. The secret or UUID cannot be changed.
     * @param key The API key to be updated. (required)
     * @param apiKeyChange The new values to apply. (required)
     * @return ApiResponse&lt;ApiError&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<ApiError> updateApiKeyWithHttpInfo(String key, ApiKeyChangeRequest apiKeyChange) throws ApiException {
        com.squareup.okhttp.Call call = updateApiKeyValidateBeforeCall(key, apiKeyChange, null, null);
        Type localVarReturnType = new TypeToken<ApiError>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Update API keys (asynchronously)
     * API keys can be updated with new labels, and be activated and deactivated. The secret or UUID cannot be changed.
     * @param key The API key to be updated. (required)
     * @param apiKeyChange The new values to apply. (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call updateApiKeyAsync(String key, ApiKeyChangeRequest apiKeyChange, final ApiCallback<ApiError> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = updateApiKeyValidateBeforeCall(key, apiKeyChange, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<ApiError>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
}
