/*
 * ID4i API
 * HTTP API Documentation for ID4i
 *
 * OpenAPI spec version: 0.0.1-alpha
 * Contact: info@bluerain.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.id4i.api;

import de.id4i.ApiException;
import de.id4i.api.model.ApiError;
import de.id4i.api.model.ApiKeyCreationRequest;
import de.id4i.api.model.ApiKeyPresentation;
import de.id4i.api.model.ApiKeyPrivilegeResponse;
import de.id4i.api.model.ApiKeyStatus;
import de.id4i.api.model.PaginatedApiKeyResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ApiKeysApi
 */
@Ignore
public class ApiKeysApiTest {

    private final ApiKeysApi api = new ApiKeysApi();

    
    /**
     * Create apiKey
     *
     * Creation of a new apiKey.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createNewApiKeyTest() throws ApiException {
        ApiKeyCreationRequest creationRequest = null;
        String authorization = null;
        String acceptLanguage = null;
        ApiKeyPresentation response = api.createNewApiKey(creationRequest, authorization, acceptLanguage);

        // TODO: test validations
    }
    
    /**
     * Delete apiKey
     *
     * Deletion of an apiKey.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteApiKeyTest() throws ApiException {
        String key = null;
        String authorization = null;
        String acceptLanguage = null;
        ApiError response = api.deleteApiKey(key, authorization, acceptLanguage);

        // TODO: test validations
    }
    
    /**
     * Show apiKey
     *
     * Showing the details of an apiKey.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getApiKeyTest() throws ApiException {
        String key = null;
        String authorization = null;
        String acceptLanguage = null;
        ApiKeyPresentation response = api.getApiKey(key, authorization, acceptLanguage);

        // TODO: test validations
    }
    
    /**
     * Find apiKeys by organization
     *
     * Finding all apiKeys assigned to the specified organization in a paginated manner.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listAllApiKeysOfOrganizationTest() throws ApiException {
        Long organizationId = null;
        String authorization = null;
        String acceptLanguage = null;
        Integer offset = null;
        Integer limit = null;
        PaginatedApiKeyResponse response = api.listAllApiKeysOfOrganization(organizationId, authorization, acceptLanguage, offset, limit);

        // TODO: test validations
    }
    
    /**
     * List ApiKey privileges
     *
     * Listing api key privileges.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listApiKeyPrivilegesTest() throws ApiException {
        String authorization = null;
        String acceptLanguage = null;
        Boolean id4nConcerning = null;
        Integer offset = null;
        Integer limit = null;
        ApiKeyPrivilegeResponse response = api.listApiKeyPrivileges(authorization, acceptLanguage, id4nConcerning, offset, limit);

        // TODO: test validations
    }
    
    /**
     * Set apiKey activation state
     *
     * Setting the apiKey activation state.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void setApiKeyActivationStatusTest() throws ApiException {
        String key = null;
        ApiKeyStatus apiKeyStatus = null;
        String authorization = null;
        String acceptLanguage = null;
        ApiError response = api.setApiKeyActivationStatus(key, apiKeyStatus, authorization, acceptLanguage);

        // TODO: test validations
    }
    
}
